version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jsm
      - POSTGRES_PASSWORD=123

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  postgres:
  mongo: